name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with: 
          platforms: linux/amd64,linux/arm64
      - name: Build PHP 8.1-cli
        uses: docker/build-push-action@v5
        with:
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          context: ./php/8.1/cli
          push: true
          tags: php:8.1-cli
